package edu.uab.model;

import org.springframework.data.annotation.Id;
import org.springframework.data.mongodb.core.mapping.Document;

@Document(collection = "courses")
public class CourseModel {
    @Id
    private String courseID; // Autogenerated ID

    private String courseName; // Name of course

    // Test Constructor
    public CourseModel(String courseID, String courseName) {
        this.courseID = courseID;
        this.courseName = courseName;
    }

    // Test Getters
    public String getID() {
        return courseID;
    }

    public String getName() {
        return courseName;
    }

    // Test Setters
    public void setID(String newID) {
        this.courseID = newID;
    }

    public void setName(String newName) {
        this.courseName = newName;
    }

    // toString method
    @Override
    public String toString() {
        return "Course{" + "Course ID='" + courseID + '\'' + ", Course Name='" + courseName + '\'' + '}';
    }

}
